Implementação cloudinary
ame-e-doe/ame-e-doe-api pull request #17
Opened 2022-08-26 00:24 UTC by RennanSilvaCosta

Nesse commit foi feito:

* Adição da dependencia do cloudinary;
* Criação da entidade Image e todo mapeamento da mesma
* Tratamento de exceções comuns do cloudinary, como arquivo inválido e de tamanho superior a 1MB
* Relacionamento entre as entidades 'IMAGE' e 'DIGITAL PRODUCT'

Tarefa refente a issue: #16

2022-08-26 14:29 UTC, edsonrepository requested changes

2022-08-27 14:18 UTC, RennanSilvaCosta commented on pom.xml
Feito.

2022-08-27 14:21 UTC, RennanSilvaCosta commented on src/main/java/br/com/loveanddonateapi/LoveAndDonateApiApplication.java
> +				"cloud_name", "dpeowsyur",
Eu só consegui fazer isso usando a anotação @value, como é utilizado na classe do JWTUtils, da outra meneira ao usar o Cloudinary ele não reconhece as variaveis e acusa erro. Acho que desse jeito atende por enquanto.

2022-08-27 14:21 UTC, RennanSilvaCosta commented on src/main/java/br/com/loveanddonateapi/controller/ImageController.java
> +        return ResponseEntity.ok(imageService.save(image));
Feito.

2022-08-27 14:21 UTC, RennanSilvaCosta commented on src/main/java/br/com/loveanddonateapi/controller/ImageController.java
> +        return ResponseEntity.ok().build();
Feito.

2022-08-28 19:08 UTC, edsonrepository approved these changes

2022-08-28 19:08 UTC, merged