Fluxo Carrinho de compras
ame-e-doe/ame-e-doe-api pull request #19
Opened 2022-10-06 00:48 UTC by RennanSilvaCosta

Nesse commit foi feito:

* Endpoints referentes as ações do carrinho de compras:
      - Adicionar um produto no carrinho;
      - Remover um produto do carrinho;
      - Recuperar os itens do carrinho;

* Implementação de um método para criar um carrinho, assim que um usuario cria uma conta;
* Ajuste no nome de um método no controller de categoria.

Tarefas referentes a issues: #18

2022-10-06 17:33 UTC, edsonrepository requested changes

2022-10-06 17:33 UTC, edsonrepository commented on src/main/java/br/com/loveanddonateapi/controller/CartController.java
> +        return new ResponseEntity<>(this.cartService.removeCartItem(token, cartItemId), HttpStatus.OK);
trocar o HttpStatus, ao invés de Ok, deve ser no_content, quando o recurso é DELETE devemos usar no_content.

2022-10-06 17:34 UTC, edsonrepository requested changes
atualizar a versão do pom.xml

2022-10-07 02:14 UTC, RennanSilvaCosta commented on src/main/java/br/com/loveanddonateapi/controller/CartController.java
> +        return new ResponseEntity<>(this.cartService.removeCartItem(token, cartItemId), HttpStatus.OK);
Feito.

2022-10-07 02:19 UTC, edsonrepository approved these changes

2022-10-07 02:20 UTC, merged