Edson/feat/security and patterns
ame-e-doe/ame-e-doe-api pull request #21
Opened 2022-10-10 13:58 UTC by edsonrepository

2022-10-10 18:40 UTC, RennanSilvaCosta requested changes

2022-10-10 18:40 UTC, RennanSilvaCosta commented on src/main/java/br/com/loveanddonateapi/controller/UserController.java
> +        Email mail = userService.registerUser( UserMapper.userDtoToEntity( userDTO ) );
O ideal não seria converter esse DTO na camada de serviço?

2022-10-10 18:40 UTC, RennanSilvaCosta commented on src/main/java/br/com/loveanddonateapi/service/UserService.java
> +        userRepository.save( user );
Da maneira que está mapeado atualmente, também precisamos criar um Cart vinculado com o usuário, no momento da criação do mesmo.

2022-10-10 18:46 UTC, edsonrepository commented on src/main/java/br/com/loveanddonateapi/service/UserService.java
> +        userRepository.save( user );
Vou abrir uma atividade para alterar, pois não está mapeado o Cart no objeto User.

2022-10-10 18:49 UTC, RennanSilvaCosta commented on src/main/java/br/com/loveanddonateapi/service/UserService.java
> +        userRepository.save( user );
Isso o User não conhece o Cart, você pode chamar o método 'createCart' que recebe um user como parametro, este método está no CartService.

2022-10-10 18:51 UTC, edsonrepository commented on src/main/java/br/com/loveanddonateapi/controller/UserController.java
> +        Email mail = userService.registerUser( UserMapper.userDtoToEntity( userDTO ) );
Na verdade não, pode-se fazer dessa forma, a conversão é transparente e não faz parte da regra de negócio. É só questão de escolha, inclusive é indicado fazer assim.

2022-10-11 02:41 UTC, RennanSilvaCosta approved these changes

2022-10-11 02:41 UTC, merged